name: Packer Validate

on:
  pull_request:
    paths:
      - 'packer/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Packer Template
        run: |
          cd packer
          packer validate template.json
